### PR TITLE
Reject timed out requests

### LINKED ISSUE #19: timeout option is not working
The `timeout` option does not make slow responses errors. It's because the `timeout` option of `http.request()` only emits `timeout` event when it timeouts instead of severing the request.

Because `perron` is not exposing the request object returned by `http.request()`, users cannot listen to the `timeout` event and abort the request.

### PR DESCRIPTION
**Pull request by shuhei**
Adding the following options:

- `timeout`: Reject the request when the socket has been inactive for `timeout` ms.
- `dropRequestAfter`: Reject the request when the request doesn't finish in `dropRequestAfter` ms.

Fixes #19.

### CODE REVIEW

File: lib/request.js [hunk 1]
```diff
@@ -40,6 +42,18 @@ module.exports = (options) => {
             });
         });
         request.on('error', reject);
+        request.on('timeout', () => {
+            request.abort();
+            reject(new Error('socket timeout'));
+        });
+        if (options.dropRequestAfter) {
+            setTimeout(() => {
+                if (!(res && typeof res.body === 'string')) {
```
Comment (grassator) [inline lib/request.js]: I would suggest instead of saving whole response to variable and then checking on one of the fields, to have an explicit flag like `hasRequestEnded` that is set in `bodyStream.on('end',` callback.

File: lib/request.js [hunk 2]
```diff
@@ -40,6 +42,18 @@ module.exports = (options) => {
             });
         });
         request.on('error', reject);
+        request.on('timeout', () => {
+            request.abort();
+            reject(new Error('socket timeout'));
```
Comment (grassator) [inline lib/request.js]: It would probably be nice if the error contained some context about what happened, otherwise seeing something like this in logs makes for a very hard debugging. Putting whole request info might be a bit tricky as you might have to filter out auth-related stuff, but at least having a host here would help:

```js
reject(new Error(`Socket timeout on request to ${options.host}`));
```

Comment (shuhei) [inline lib/request.js]: Yeah, it would be helpful. And I think it's same for `request.on('error', reject)`. It would be nice to add information about request in `client.js` because it gets all errors from `request.js` anyway.

Comment (grassator) [inline lib/request.js]: Makes sense, could you please create an issue on this then?

Comment (shuhei) [inline lib/request.js]: Sure, created one 😄  https://github.com/zalando-incubator/perron/issues/24

File: lib/request.js (hunk 1 above)
Comment (shuhei) [inline lib/request.js]: Changed `res` to the explicit flag.

**Comment by grassator** [comment]
@shuhei Thanks a lot for the PR. I've published 0.3.0-beta2 on NPM

**Comment by shuhei** [comment]
@grassator Thanks!
